apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: app-consult

images:
- name: appconsult
  newName: nandocloud/app-consult
  newTag: 645e789a484ff8946b01dd5e8e583b6c0d793255
- name: react-application
  newName: appconsult
  newTag: latest
