name: build
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build an image from Dockerfile
        uses: actions/checkout@v2

      - name: build image and push to docker hub
        uses: docker/build-push-action@v1.1.0
        with:
          username: nandocloud
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: nandocloud/app-consult
          tags: ${{ github.sha }}, latest
          
